app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stocks.urls')),
    path('', include('accounts.urls')),
    path('', include('collection.urls')),
    path('', include('color.urls')),
    path('', include('sizes.urls')),
    path('', include('number.urls')),
    path('', include('brand.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommecer/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

stocks/urls.py
from django.urls import path
from stocks.views import StockBaseView, StockCreateView, StockListView, StockUpdateView,StockDetailView, StockDeleteView


urlpatterns = [
    path('', StockBaseView.as_view(), name='StockBaseView'),
    path('stock/', StockListView.as_view(), name='stock_list_view'),
    path('stock/new/', StockCreateView.as_view(), name='stock_create_view'),
    path('stock/update/<int:pk>/', StockUpdateView.as_view(), name='stock_update_view'),
    path('stock/detail/<int:pk>/', StockDetailView.as_view(), name='stock_detail_view'),
    path('stock/delete/<int:pk>/', StockDeleteView.as_view(), name='stock_delete_view'),
]

number/models.py
from django.db import models
from stocks.models import Stock


class Number(models.Model):
    name_number = models.CharField(max_length=4)

    def __str__(self):
        return self.name_number


class NumberQuantity(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='number_quantities')
    number = models.ForeignKey(Number, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)


    class Meta:
        unique_together = ('stock', 'number')  
    
    def __str__(self):
       return f"{self.stock.name} - {self.number.name_number}: {self.quantity}"

sizes/models.py
from django.db import models
from stocks.models import Stock

class Size(models.Model):
    size = models.CharField(max_length=10, unique=True)
   
    def __str__(self):
        return self.size


class SizeQuantity(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='size_quantities')
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        unique_together = ('stock', 'size')  # Evita duplicatas

    def __str__(self):
        return f"{self.stock.name} - {self.size.size}: {self.quantity}"

stocks/models.py
from django.db import models
from collection.models import Collection
from color.models import Color
from brand.models import Brand


class Stock(models.Model):

    name = models.CharField(max_length=200)
    barcode = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    images_0 = models.ImageField(upload_to='media/', blank=True, null=True)
    images_1 = models.ImageField(upload_to='media/', blank=True, null=True)
    images_2 = models.ImageField(upload_to='media/', blank=True, null=True)
    images_3 = models.ImageField(upload_to='media/', blank=True, null=True)
    price = models.CharField(blank=True, null=True, max_length=200)
    quantity = models.CharField(max_length=13, blank=True, null=True)
    color = models.ManyToManyField(Color , related_name='stocks')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    category = models.CharField(max_length=50, blank=True, null=True)
    collections = models.ManyToManyField(Collection, related_name='collections')
    variations = models.CharField(max_length=200, blank=True, null=True) 
    number_active = models.BooleanField(default=True)
    size_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

stocks/forms.py
from django import forms
from stocks.models import Stock
from sizes.models import Size, SizeQuantity
from number.models import Number, NumberQuantity


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = "__all__"
        widgets = {
            'collections': forms.CheckboxSelectMultiple(),
            'color': forms.CheckboxSelectMultiple(),
            'images_0': forms.ClearableFileInput(attrs={'class': 'imgs'}),
            'images_1': forms.ClearableFileInput(attrs={'class': 'imgs'}),
            'images_2': forms.ClearableFileInput(attrs={'class': 'imgs'}),
            'images_3': forms.ClearableFileInput(attrs={'class': 'imgs'}),
            'price': forms.TextInput(attrs={'oninput': 'mascaraMoeda(event)'}),
        }
        help_texts = {
            'name': 'Nome do Produto',
            'description': 'Descrição do estoque',
            'image': 'Imagem do estoque',
        }
        error_messages = {
            'name': {
                'max_length': "O nome do estoque é muito longo.",
            },
            'description': {
                'max_length': "A descrição do estoque é muito longa.",
            },
        }
      
    def clean_price(self):
        price = str(self.cleaned_data.get('price'))
        price = price.replace(',', '.') 
        try:
            price = float(price)
        except ValueError:
            raise forms.ValidationError("Preço inválido. Use o formato correto.")
        return price
       
        

class DynamicSizeQuantityForm(forms.Form):
    def __init__(self, *args, stock_instance=None, **kwargs):
        self.stock_instance = stock_instance
        super().__init__(*args, **kwargs)

        sizes = Size.objects.all()
        existing_quantities = {}

        if self.stock_instance:
            # Pega as quantidades existentes relacionadas ao stock
            size_quantities = SizeQuantity.objects.filter(stock=self.stock_instance)
            existing_quantities = {
                sq.size.id: sq.quantity for sq in size_quantities
            }

        for size in sizes:
            self.fields[f'use_size_{size.id}'] = forms.BooleanField(
                label=f"{size.size}",
                required=False,
                initial=(size.id in existing_quantities)
            )
            self.fields[f'quantity_{size.id}'] = forms.IntegerField(
                label="",
                min_value=0,
                required=False,  # Deixar opcional
                # initial=existing_quantities.get(size.id, 0)  # Garantir que tenha valor inicial
            )


class DynamicNumberQuantityForm(forms.Form):
    def __init__(self, *args, stock_instance=None, **kwargs):
        self.stock_instance = stock_instance
        super().__init__(*args, **kwargs)

        numbers = Number.objects.all()
        existing_quantities = {}

        if self.stock_instance:
            # Pega as quantidades existentes relacionadas ao stock
            number_quantities = NumberQuantity.objects.filter(stock=self.stock_instance)
            existing_quantities = {
                nq.number.id: nq.quantity for nq in number_quantities
            }

        for number in numbers:
            self.fields[f'use_number_{number.id}'] = forms.BooleanField(
                label=f"{number.name_number}",
                required=False,
                initial=(number.id in existing_quantities)
            )
            self.fields[f'quantity_{number.id}'] = forms.IntegerField(
                label='',
                min_value=0,
                required=False,  # Deixar opcional
                # initial=existing_quantities.get(number.id, 0)  # Garantir que tenha valor inicial
            )

stocks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from stocks.models import Stock 
from sizes.models import Size, SizeQuantity
from number.models import Number, NumberQuantity
from stocks.forms import StockForm, DynamicSizeQuantityForm, DynamicNumberQuantityForm


class StockBaseView(View):
    def get(self, request):
        # Renderiza o template com os dados necessários
        return render(request, 'base.html')
        # Renderiza o template com os dados necessários


@method_decorator(login_required(login_url="login"), name='dispatch')
@method_decorator(user_passes_test(lambda u: u.is_superuser, login_url="login"), name='dispatch')
class StockListView(ListView):
    model = Stock
    template_name = "stock.html"
    context_object_name = "stocks"

    def get_queryset(self):
        # pega o search
        stock = super().get_queryset().order_by('name',)
        search = self.request.GET.get('search')
        if search:
            stock = Stock.objects.filter(name__icontains=search, ).order_by('name', 'collections')
        return stock



@method_decorator(login_required(login_url="login"), name='dispatch')
@method_decorator(user_passes_test(lambda u: u.is_superuser, login_url="stock_list_view"), name='dispatch')
class StockCreateView(CreateView):
    model = Stock
    form_class = StockForm
    template_name = 'stock_create.html'
    success_url = '/stock/'
    
    def get(self, request, *args, **kwargs):
        stock_form = self.form_class()
        size_form = DynamicSizeQuantityForm()
        number_form = DynamicNumberQuantityForm()
        return render(request, self.template_name, {'form': stock_form, 'size_form': size_form, 'number_form': number_form})

    def post(self, request, *args, **kwargs):
        stock_form = self.form_class(request.POST, request.FILES)
        size_form = DynamicSizeQuantityForm(request.POST)
        number_form = DynamicNumberQuantityForm(request.POST)

        if stock_form.is_valid() and size_form.is_valid() and number_form.is_valid():
            stock = stock_form.save()

            for size in Size.objects.all():
                use_size = size_form.cleaned_data.get(f'use_size_{size.id}')
                quantity = size_form.cleaned_data.get(f'quantity_{size.id}')
                if use_size and quantity is not None:
                    SizeQuantity.objects.create(
                        stock=stock,
                        size=size,
                        quantity=quantity
                    )

            for number in Number.objects.all():
                use_number = number_form.cleaned_data.get(f'use_number_{number.id}')
                quantity = number_form.cleaned_data.get(f'quantity_{number.id}')
                if use_number and quantity is not None:
                    NumberQuantity.objects.create(
                        stock=stock,
                        number=number,
                        quantity=quantity
                    )
                    return redirect(self.get_success_url())

        return render(request, self.template_name, {'form': stock_form, 'size_form': size_form, 'number_form': number_form})

    def get_success_url(self):
            action = self.request.POST.get('action')
            if action == 'save_add':
                return reverse_lazy('stock_create_view')  
            else:
                return reverse_lazy('stock_list_view')  


@method_decorator(login_required(login_url="login"), name='dispatch')
@method_decorator(user_passes_test(lambda u: u.is_superuser, login_url="login"), name='dispatch')
class StockUpdateView(UpdateView):
    model = Stock
    form_class = StockForm
    template_name = 'stock_update.html'
    success_url = '/stock/'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        stock_form = self.form_class(instance=self.object)
        size_form = DynamicSizeQuantityForm(stock_instance=self.object)
        number_form = DynamicNumberQuantityForm(stock_instance=self.object)
        return render(request, self.template_name, {'form': stock_form, 'size_form': size_form, 'number_form': number_form})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        stock_form = self.form_class(request.POST, request.FILES, instance=self.object)
        size_form = DynamicSizeQuantityForm(request.POST, stock_instance=self.object)
        number_form = DynamicNumberQuantityForm(request.POST, stock_instance=self.object)
        
        if stock_form.is_valid() and size_form.is_valid() and number_form.is_valid():
            stock = stock_form.save()

            # Limpa e recria os SizeQuantities (ou atualiza)
            for size in Size.objects.all():
                use_size = size_form.cleaned_data.get(f'use_size_{size.id}')
                quantity = size_form.cleaned_data.get(f'quantity_{size.id}')

                if use_size and quantity is not None:
                    sq, created = SizeQuantity.objects.get_or_create(
                        stock=stock,
                        size=size,
                        defaults={'quantity': quantity}
                    )
                    if not created:
                        sq.quantity = quantity
                        sq.save()
                else:
                    # Se estava marcado antes e desmarcou agora, remove
                    SizeQuantity.objects.filter(stock=stock, size=size).delete()
            
            for number in Number.objects.all():
                use_number = number_form.cleaned_data.get(f'use_number_{number.id}')
                quantity = number_form.cleaned_data.get(f'quantity_{number.id}')

                if use_number and quantity is not None:
                    nq, created = NumberQuantity.objects.get_or_create(
                        stock=stock,
                        number=number,
                        defaults={'quantity': quantity}
                    )
                    if not created:
                        nq.quantity = quantity
                        nq.save()
                else:
                    # Se estava marcado antes e desmarcou agora, remove
                    NumberQuantity.objects.filter(stock=stock, number=number).delete()
            return redirect(self.success_url)

        return render(request, self.template_name, {'form': stock_form, 'size_form': size_form})


@method_decorator(login_required(login_url="login"), name='dispatch')
@method_decorator(user_passes_test(lambda u: u.is_superuser, login_url="login"), name='dispatch')
class StockDeleteView(DeleteView):
    model = Stock
    template_name = 'stock_delete.html'
    success_url = '/stock/'


@method_decorator(login_required(login_url="login"), name='dispatch')
@method_decorator(user_passes_test(lambda u: u.is_superuser, login_url="login"), name='dispatch')
class StockDetailView(DetailView):
    model = Stock
    template_name = 'stock_detail.html'
    success_url = '/stock/'

stocks/templates/stock.html
{% extends 'base.html' %} {% block title %} Produtos {% endblock %}
{% block content %}

<section class="section">
    <div class="produtos">
        {% if stocks %}
        <div class="container-itens">
            {% for stock in stocks %}
            <a href="{% url 'stock_detail_view' stock.pk %}">
                <div class="container-item">
                    <div class="container-text">
                        <p class="title">{{ stock.name }}</p>
                        <p>{{ stock.description }}</p>
                        <p>R$ {{ stock.price }}</p>
                    </div>

                    <div class="container-imagens">
                        {% if stock.images_0 %}
                        <img src=" {{ stock.images_0.url }}" alt="Imagem 1">
                        {% else %}
                        {% if stock.images_1 %}
                        <img src=" {{ stock.images_1.url }}" alt="Imagem 1">
                        {% else %}
                        {% if stock.images_2 %}
                        <img src=" {{ stock.images_0.url }}" alt="Imagem 1">
                        {% else %}
                        {% if stock.images_3 %}
                        <img src=" {{ stock.images_3.url }}" alt="Imagem 1">
                        {% else %}
                        <img src="/static/media/sem_imagem_sem_fundo.png" alt="Imagem Não encontrada">
                        <p>Imagem não Encontrada</p>

                        {% endif %}{% endif %} {% endif %}{% endif %}
                    </div>

                </div>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <p>Nenhum item encontrado.</p>
        {% endif %}
    </div>
</section>

{% endblock %}

stocks/templates/stock_create.html
{% extends 'base.html' %}

{% block title %}
Adicionar Produto {% endblock %}
<style>

</style>
{% block content %}
<section class="container-new">
    <h2>Adicionar Novo Produto</h2>

    <form method="post" enctype="multipart/form-data">

        <div class="form-new">

            {% csrf_token %}

            <div class="container-itens">
                <label for="id_name">Produto {{ form.name }}</label>
                <label for="id_barcode">Codigo de barras {{form.barcode }}</label>
                <label for="id_description"> Descrição {{ form.description }}</label>
                <label for="id_images"> imagens
                    <div class="imagens" id="id_images">
                        <label for="id_images_0" class="label-img"> imagen 1 {{ form.images_0 }}</label>
                        <label for="id_images_1" class="label-img">imagen 2 {{ form.images_1 }} </label>
                        <label for="id_images_2" class="label-img"> imagen 3 {{ form.images_2 }}</label>
                        <label for="id_images_3" class="label-img">imagen 4{{ form.images_3 }}</label>
                    </div>
                </label>

                <label for="id_price"> preço {{ form.price }}</label>
                <label for="id_quantity">quantidade {{ form.quantity }}</label>
                <label for="id_color">cores {{ form.color }}</label>
                <label for="id_brand"> marca {{ form.brand }}</label>
                <label for="id_category">categoria {{ form.category }}</label>
                <label for="id_collections"> coleções {{ form.collections }}</label>
                <label for="id_variations"> variações {{ form.variations }}</label>
                <label for="id_number_active"> mostrar Numeração {{ form.number_active }}</label>
                <label for="id_size_active">mostrar Tamanhos {{ form.size_active }}</label>

            </div>

            <div class="container-size">
                <label> Tamanhos </label>
                {% for field in size_form %}

                {{ field.label_tag }} {{ field }}

                {% endfor %}
            </div>

            <div class="container-number">
                <label> Numerações </label>
                {% for numbers in number_form %}

                {{ numbers.label_tag }} {{ numbers }}

                {% endfor %}
            </div>
        </div>

        <div class="buttons">
            <button type="submit" class="bnt bnt-salvar" name="action" value="save_add">Salvar e adicionar
                outro</button>
            <button type="submit" class="bnt bnt-salvar" name="action" value="save_list">Salvar e ir para lista</button>
            <a href="{% url 'stock_list_view'%}" class="bnt bnt-cancelar"> cancelar</a>
        </div>
    </form>

    {% if form.errors %}
    <div class="error-messages">
        <ul>
            {% for field, errors in form.errors.items %}
            <li>
                <strong>{{ field|capfirst }}:</strong>
                {% for error in errors %}
                {{ error }}
                {% endfor %}
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</section>

{% endblock %}
<script>
    const mascaraMoeda = (event) => {
        const onlyDigits = event.target.value.replace(/\D/g, "").padStart(3, "0");
        const digitsFloat = onlyDigits.slice(0, -2) + "." + onlyDigits.slice(-2);
        event.target.value = maskCurrency(digitsFloat);
    };

    const maskCurrency = (valor, locale = "pt-BR", currency = "BRL") => {
        return new Intl.NumberFormat(locale, { minimumFractionDigits: 2 }).format(
            valor
        );
    };

</script>

stocks/templates/stock_delete.html
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'stock_update_view' pk=stock.pk %}" class="btn btn-secondary">Cancelar</a>
</form>

stocks/templates/stock_detail.html
{% extends 'base.html' %} {% block title %} Produto object.name {% endblock %}
{% block content %}
<div class="container-item">
    <div class="container-text">
        <p class="title">{{ object.name }}</p>
        <p>{{ object.description }}</p>
        <p>R$ {{ object.price }}</p>
        {% if object.number_active %}
        <p>Numeração {{ object.number_form }}</p>

        </p>
        {% else %}
    </div>

    <div class="container-imagens">
        {% if object.images_0 %}
        <img src=" {{ stock.images_0.url }}" alt="Imagem 1">
        {% else %}
        {% if object.images_1 %}
        <img src=" {{ stock.images_1.url }}" alt="Imagem 1">
        {% else %}
        {% if object.images_2 %}
        <img src=" {{ stock.images_0.url }}" alt="Imagem 1">
        {% else %}
        {% if object.images_3 %}
        <img src=" {{ stock.images_3.url }}" alt="Imagem 1">
        {% else %}
        <img src="/static/media_local/sem_imagem_sem_fundo.png" alt="Imagem Não encontrada">
        <p>Imagem não Encontrada</p>

        {% endif %}{% endif %} {% endif %}{% endif %}{% endif %}
    </div>
    <div class="buttons-container">
        <a href="{% url 'stock_update_view' pk=object.pk %}" class="btn btn-primary">Editar</a>
        <a href="{% url 'stock_delete_view' pk=object.pk %}" class="btn btn-danger">Deletar</a>
    </div>

</div>
{% endblock %}

stocks/templates/stock_new1.html
{% extends "base.html" %}{% block title %}Adicionar Novo Produto{% endblock %}
{% block content %}
<style>
    .imagens {
        display: flex;
        gap: 10px;
    }
</style>


<section class="section-new-product">
    <h1>Cadastrar Novo Produto</h1>

    <form method="post" enctype="multipart/form-data" class="form-new-product">
        {% csrf_token %}

        <div class="container-new-product">
            <label for="id_name">nome</label>
            {{ form.name }}

            <label for="id_description">Descrição</label>
            {{ form.description }}

            <label for="id_price">preço</label>
            {{ form.price }}

            <label for="id_quantity">quantidade</label>
            {{ form.quantity }}


            <label for="id_variations">Variações</label>
            {{ form.variations }}


            <div class="list">
                <label for="id_size">Tamanhos</label>
                {{ form.size }}
                {{ form.size_quantity }}
            </div>

            <div class="list">
                <label for="id_number">números</label>
                {{ form.number }}
            </div>

            <div class="list">
                <label for="id_collections">Coleções</label>
                {{ form.collections }}
            </div>
        </div>

        <div class="imagens_preview">
            <img id="preview_0" style="max-width: 300px; display: none;">
            <button type="button" id="remove_0" style="display: none;">Remover imagem</button>
            <img id="preview_1" style="max-width: 300px; display: none;">
            <button type="button" id="remove_1" style="display: none;">Remover imagem</button>
            <img id="preview_2" style="max-width: 300px; display: none;">
            <button type="button" id="remove_2" style="display: none;">Remover imagem</button>
            <img id="preview_3" style="max-width: 300px; display: none;">
            <button type="button" id="remove_3" style="display: none;">Remover imagem</button>
        </div>
        <div class="imagens">
            {{ form.images_0 }}
            {{ form.images_1 }}
            {{ form.images_2 }}
            {{ form.images_3 }}
        </div>

        <button type="submit">Salvar Produto</button>
    </form>
    </div>


</section>


<script>
    function previewImagemComRemover(inputId, previewId, removeBtnId) {
        const input = document.getElementById(inputId);
        const preview = document.getElementById(previewId);
        const removeBtn = document.getElementById(removeBtnId);

        input.addEventListener('change', function (event) {
            const file = event.target.files[0];

            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                    removeBtn.style.display = 'inline-block'; // Mostra botão
                }
                reader.readAsDataURL(file);
            } else {
                limparImagem();
            }
        });

        removeBtn.addEventListener('click', function () {
            limparImagem();
        });

        function limparImagem() {
            input.value = ''; // Limpa o input file
            preview.src = '';
            preview.style.display = 'none';
            removeBtn.style.display = 'none';
        }
    }

    // Chamando a função
    previewImagemComRemover('id_images_0', 'preview_0', 'remove_0');
    previewImagemComRemover('id_images_1', 'preview_1', 'remove_1');
    previewImagemComRemover('id_images_2', 'preview_2', 'remove_2');
    previewImagemComRemover('id_images_3', 'preview_3', 'remove_3');


    // Função auxiliar para criar FileList
    const mascaraMoeda = (event) => {
        const onlyDigits = event.target.value.replace(/\D/g, "").padStart(3, "0");
        const digitsFloat = onlyDigits.slice(0, -2) + "." + onlyDigits.slice(-2);
        event.target.value = maskCurrency(digitsFloat);
    };

    const maskCurrency = (valor, locale = "pt-BR", currency = "BRL") => {
        return new Intl.NumberFormat(locale, { minimumFractionDigits: 2 }).format(
            valor
        );
    };

</script>
{% endblock %}

stocks/templates/stock_update.html
{% if form.errors %}
<div class="form-errors">
    <ul>
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <h3>Tamanhos e Quantidades</h3>
    {% for field in size_form %}
    <div style="margin-bottom: 10px">
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}

    <h3>Números e Quantidades</h3>
    {% for numbers in number_form %}
    <div style="margin-bottom: 10px">
        {{ numbers.label_tag }} {{ numbers }}
    </div>
    {% endfor %}
    <button type="submit">Atualizar</button>
</form>

stocks/templates/stock_update1.html
{% extends "base.html" %}{% block title %}Adicionar Novo Produto{% endblock %}
{% block content %}

<section class="section-new-product">
    <h1> Atualizar Produto</h1>

    <div class="container-form">
        <div>

            <div id="image-preview-container" class="img-preview"></div>
        </div>

        <div>
            <form method="post" enctype="multipart/form-data" class="form-new-product">
                {% csrf_token %}
                <h3>Informações do Produto</h3>

                <div class="container-new-product">
                    {{ form.as_p}}
                </div>
                <br>
                <button type="submit">Salvar Produto</button>
            </form>
        </div>
    </div>



</section>


<script>


    // Função auxiliar para criar FileList
    const mascaraMoeda = (event) => {
        const onlyDigits = event.target.value.replace(/\D/g, "").padStart(3, "0");
        const digitsFloat = onlyDigits.slice(0, -2) + "." + onlyDigits.slice(-2);
        event.target.value = maskCurrency(digitsFloat);
    };

    const maskCurrency = (valor, locale = "pt-BR", currency = "BRL") => {
        return new Intl.NumberFormat(locale, { minimumFractionDigits: 2 }).format(
            valor
        );
    };

</script>
{% endblock %}